version: 2.1

orbs:
  maven: circleci/maven@1.3.0
  node: circleci/node@5.0.2
  docker: circleci/docker@1
  k8s: digitalocean/k8s@0.1.1

jobs:
  mvn-build:
    executor: maven/default
    steps:
      - checkout
      - run:
          name: maven build producer service
          command: mvn -f walking\ skeleton/services/service-producer/pom.xml clean package -DskipTests
      - run:
          name: maven build consumer service
          command: mvn -f walking\ skeleton/services/service-consumer/pom.xml clean package -DskipTests
      - run:
          name: maven build gateway
          command: mvn -f walking\ skeleton/services/gateway/pom.xml clean package -DskipTests
  
  npm-build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run:
          name: npm install and test
          command: npm -f walking\ skeleton/services/frontend/package-lock.json cit
      - run: 
          name: npm build frontend
          command: npm -f walking\ skeleton/services/frontend/package-lock.json build

  dockerhub-deploy:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn -f walking\ skeleton/services/service-producer/pom.xml clean package -DskipTests
      - setup_remote_docker
      - checkout
      - docker/check
      - run: mvn -f walking\ skeleton/services/service-producer/pom.xml compile jib:dockerBuild -Djib.to.image=$DOCKER_USER/skeleton-service-producer -Djib.to.tags=$CIRCLE_SHA1
      - docker/push: 
          image: $DOCKER_USER/skeleton-service-producer
          tag: "latest,$CIRCLE_SHA1"

workflows:
  build-and-publish:
    jobs:
      - mvn-build
      - npm-build
      - dockerhub-deploy:
          requires:
            - mvn-build
            - npm-build
