version: 2.1

orbs:
  maven: circleci/maven@1.0.3
  docker: circleci/docker@1
  k8s: digitalocean/k8s@0.1.1

jobs:
  mvn-build:
    executor: maven/default
    steps:
      - checkout
      - run:
          name: maven build producer service
          command: mvn -f walking-skeleton/services/service-producer/pom.xml test
  
  dockerhub-deploy:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn -f walking-skeleton/services/service-producer/pom.xml clean package -DskipTests
      - setup_remote_docker
      - checkout
      - docker/check
      - run: mvn compile jib:dockerBuild -Djib.to.auth.username=${DOCKER_USER} -Djib.to.auth.password=${DOCKER_PASSWORD} -Djib.to.image=${DOCKER_USER}/skeleton-service-producer -Djib.to.tags=$CIRCLE_SHA1
      - docker/push: 
          image: ${DOCKER_USER}/skeleton-service-producer
          tag: "latest,$CIRCLE_SHA1"



workflows:
  build-and-publish:
    jobs:
      - mvn-build
      - dockerhub-deploy:
        requires:
          - build
#        filters:
#          branches:
#            only:
#              - main
