global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - "alertmanager:9091"

# ? kijken of ik via discovery de prometheus kan ophalen ipv iedere service apart vermelden
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'gateway'
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway:8081']
  - job_name: 'producer'
    scrape_interval: 5s
    metrics_path: /gateway/producer/actuator/prometheus
    static_configs:
      - targets: ['gateway:8081']
  - job_name: 'consumer'
    scrape_interval: 5s
    metrics_path: /gateway/consumer/actuator/prometheus
    static_configs: 
      - targets: ['gateway:8081']