apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-1
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
      - name: kafka-1
        image: confluentinc/cp-kafka:6.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: LISTENER_INTERNAL://kafka-1:9092
          #value: LISTENER_INTERNAL://kafka-1:19092,LISTENER_DOCKERHOST://localhost:29092,LISTENER_EXTERNAL://127.0.0.1:9092
#        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
#          value: "False"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_BROKER_RACK
          value: r1
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "True"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "100"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: LISTENER_INTERNAL
        # - name: KAFKA_JMX_HOSTNAME
        #   value: 127.0.0.1
        # - name: KAFKA_JMX_OPTS
        #   value: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9992
        # - name: KAFKA_JMX_PORT
        #   value: "9992"
        - name: KAFKA_LISTENERS
          value: LISTENER_INTERNAL://kafka-1:9092
          #value: LISTENER_INTERNAL://kafka-1:19092,LISTENER_DOCKERHOST://kafka-1:29092,LISTENER_EXTERNAL://kafka-1:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: LISTENER_INTERNAL:PLAINTEXT,LISTENER_DOCKERHOST:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
        - name: KAFKA_MESSAGE_TIMESTAMP_TYPE
          value: CreateTime
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-1:2181
        - name: KAFKA_CREATE_TOPICS
          value: test-topic
      hostname: kafka-1
      restartPolicy: Always