apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafkacat
  name: kafkacat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkacat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafkacat
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              apk add jq;
              while [ 1 -eq 1 ];do sleep 60;done
          image: edenhill/kafkacat:1.6.0
          name: kafkacat
      hostname: kafkacat
      restartPolicy: Always